package org.streaming.job;
/**
 * POJO representing a record of FlashSaleEvent. Here we have the data that is expected in the mock.
 * The situation is of records being generated by users buying products in our ecommerce platform.
 * So, in our mocked system we would have the data being generated by the user in contact with the platform,
 * an event timestamp and also an apitimestamp to indicate when this data was ingested by the api system.
 * Moreover, we have the business fields that are used to gather information about how much a custumer is
 * spending when buying in our ecommerce platform, how many products and the vat that he is paying for this.
 */
public class FlashSaleEvent {
    public String eventId;
    public String eventTimestamp;
    public String apiTimestamp;
    public String operationId;
    public String orderNumber;
    public boolean isCancelled;
    public String clientId;
    public int units;
    public double totalPrice;
    public double totalVatAmount;
    public String flashSaleId;
    public String flashSaleGoalId;

    public FlashSaleEvent(String eventId, String eventTimestamp, String apiTimestamp, String operationId,
                          String orderNumber, boolean isCancelled, String clientId, int units,
                          double totalPrice, double totalVatAmount, String flashSaleId, String flashSaleGoalId) {
        this.eventId = eventId;
        this.eventTimestamp = eventTimestamp;
        this.apiTimestamp = apiTimestamp;
        this.operationId = operationId;
        this.orderNumber = orderNumber;
        this.isCancelled = isCancelled;
        this.clientId = clientId;
        this.units = units;
        this.totalPrice = totalPrice;
        this.totalVatAmount = totalVatAmount;
        this.flashSaleId = flashSaleId;
        this.flashSaleGoalId = flashSaleGoalId;
    }

    @Override
    public String toString() {
        return "FlashSaleEvent{" +
                "eventId='" + eventId + '\'' +
                ", eventTimestamp='" + eventTimestamp + '\'' +
                ", apiTimestamp='" + apiTimestamp + '\'' +
                ", operationId='" + operationId + '\'' +
                ", orderNumber='" + orderNumber + '\'' +
                ", isCancelled=" + isCancelled +
                ", clientId='" + clientId + '\'' +
                ", units=" + units +
                ", totalPrice=" + totalPrice +
                ", totalVatAmount=" + totalVatAmount +
                ", flashSaleId='" + flashSaleId + '\'' +
                ", flashSaleGoalId='" + flashSaleGoalId + '\'' +
                '}';
    }

    // Those were implemented because I dont know about how I would extend this project.
    public String getEventId() {
        return eventId;
    }

    public void setEventId(String eventId) {
        this.eventId = eventId;
    }

    public String  getEventTimestamp() {
        return eventTimestamp;
    }

    public void setEventTimestamp(String eventTimestamp) {
        this.eventTimestamp = eventTimestamp;
    }

    public String getApiTimestamp() {
        return apiTimestamp;
    }

    public void setApiTimestamp(String apiTimestamp) {
        this.apiTimestamp = apiTimestamp;
    }

    public String getOperationId() {
        return operationId;
    }

    public void setOperationId(String operationId) {
        this.operationId = operationId;
    }

    public String getOrderNumber() {
        return orderNumber;
    }

    public void setOrderNumber(String orderNumber) {
        this.orderNumber = orderNumber;
    }

    public boolean isCancelled() {
        return isCancelled;
    }

    public void setCancelled(boolean cancelled) {
        isCancelled = cancelled;
    }

    public String getClientId() {
        return clientId;
    }

    public void setClientId(String clientId) {
        this.clientId = clientId;
    }

    public int getUnits() {
        return units;
    }

    public void setUnits(int units) {
        this.units = units;
    }

    public double getTotalPrice() {
        return totalPrice;
    }

    public void setTotalPrice(double totalPrice) {
        this.totalPrice = totalPrice;
    }

    public double getTotalVatAmount() {
        return totalVatAmount;
    }

    public void setTotalVatAmount(double totalVatAmount) {
        this.totalVatAmount = totalVatAmount;
    }

    public String getFlashSaleId() {
        return flashSaleId;
    }

    public void setFlashSaleId(String flashSaleId) {
        this.flashSaleId = flashSaleId;
    }

    public String getFlashSaleGoalId() {
        return flashSaleGoalId;
    }

    public void setFlashSaleGoalId(String flashSaleGoalId) {
        this.flashSaleGoalId = flashSaleGoalId;
    }
}